[package]
name = "v_escape"
version = "0.15.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "The simd optimized escaping code"
documentation = "https://docs.rs/v_escape"
edition = "2018"
keywords = ["escaping", "simd"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/v_escape"
workspace = ".."

[badges]
travis-ci = { repository = "botika/v_escape", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["bytes-buf-tokio2"]
bytes-buf-tokio2 = ["buf-min/bytes-buf-tokio2"]
bytes-buf-tokio3 = ["buf-min/bytes-buf-tokio3"]

[dependencies]
v_escape_derive = { version = "~0.8.4", path = "../v_escape_derive" }
buf-min = { version = "0.4", optional = true }

[dev-dependencies]
bytes = "1.0"
# TODO: Coverage with both versions
buf-min = { version = "0.4", features = ["bytes-buf-tokio3"] }
